//array of random adjectives 
const randomAdjectiveArray = [
    'amazing',
    'apathetic',
    'arrogant',
    'belligerent',
    'benevolent',
    'boring',
    'ballsy',
    'brave',
    'casual',
    'cocky',
    'crazy',
    'cute',
    'daring',
    'dashing',
    'disgusting',
    'dumb',
    'devious',
    'eager',
    'eccentric',
    'elegant',
    'evil',
    'fearless',
    'fierce',
    'friendly',
    'funky',
    'funny',
    'furious',
    'generous',
    'gigantic',
    'gloomy',
    'goofy',
    'graceful',
    'grumpy',
    'handsome',
    'happy',
    'hilarious',
    'humble',
    'hungry',
    'ignorant',
    'insane',
    'intelligent',
    'jovial',
    'juvenile',
    'kind',
    'lazy',
    'lonely',
    'lethargic',
    'lucky',
    'magnificent',
    'maniacal',
    'mellow',
    'miserable',
    'naughty',
    'nervous',
    'nice',
    'obnoxious',
    'optimistic',
    'outrageous',
    'pitiful',
    'pompous',
    'questionable',
    'quaint',
    'rational',
    'rebellious',
    'rustic',
    'sassy',
    'savage',
    'tactful',
    'tense',
    'terrifying',
    'tired',
    'tasmanian',
    'ugly',
    'unusual',
    'vicious',
    'viscous',
    'violent',
    'wacky',
    'wasteful',
    'wobbly',
    'wonderful',
    'young',
    'zany',
    'zealous'
];

//array of random nouns
const randomNounArray = [
    'aardvark',
    'albatross',
    'alligator',
    'alpaca',
    'asshole',
    'anus',
    'asphalt',
    'axolotl',
    'acorn',
    'apple',
    'banana',
    'button',
    'bucket',
    'butt',
    'butter',
    'boogers',
    'batteries',
    'biscuit',
    'cactus',
    'cannon',
    'carrot',
    'caterpillar',
    'chicken',
    'chimichanga',
    'cat',
    'dog',
    'dolphin',
    'dinosaur',
    'disappointment',
    'dishwasher',
    'dirt',
    'donkey',
    'dumpling',
    'dust',
    'earwax',
    'egg',
    'elephant',
    'eyeball',
    'fart',
    'fairy',
    'food',
    'frog',
    'giraffe',
    'goat',
    'garbage',
    'goblin',
    'gremilin',
    'gargoyle',
    'hedgehog',
    'hippo',
    'horse',
    'hamburger',
    'ice cream',
    'iguana',
    'jellyfish',
    'jerk',
    'kangaroo',
    'koala',
    'kumquat',
    'lemon',
    'lizard',
    'llama',
    'mango',
    'monkey',
    'muffin',
    'narwhal',
    'ninja',
    'noodle',
    'octopus',
    'ostrich',
    'otter',
    'panda',
    'penguin',
    'pickle',
    'pig',
    'pigeon',
    'pizza',
    'potato',
    'puppy',
    'quail',
    'quiche',
    'ravioli',
    'rhino',
    'robot',
    'sock',
    'squirrel',
    'taco',
    'toad',
    'turd',
    'turtle',
    'unicorn',
    'vampire',
    'vulture',
    'walrus',
    'waffle',
    'weasel',
    'whale',
    'worm',
    'yearbook',
    'yogurt',
    'zebra',
    'zombie'
];

//array of random thoughts
const thots = [
    "Just had the best meal ever! #foodie #yum",
    "Feeling grateful for all the wonderful people in my life. #blessed",
    "Can't wait for the weekend! #TGIF #weekendvibes",
    "Feeling inspired to start a new project. #creativity",
    "Just finished reading an amazing book. Any recommendations? #reading",
    "Missing the beach already. #summer #vacation",
    "Excited about the upcoming concert! #musiclover #livemusic",
    "Had a productive day at work. #worklife",
    "Feeling motivated to hit the gym. #fitness",
    "Enjoying the beautiful sunset. #nature",
    "Spent the day exploring new places. #adventure #travel",
    "Feeling nostalgic today. #throwback",
    "Just adopted the cutest puppy! #doglover",
    "Watching my favorite movie for the hundredth time. #movienight",
    "Feeling proud of my achievements. #accomplishment",
    "Trying out a new recipe in the kitchen. #cooking",
    "Feeling grateful for all the love and support. #gratitude",
    "Excited about the new video game release. #gaming",
    "Feeling blessed to have such amazing friends. #friendship",
    "Celebrating a special occasion tonight. #celebration",
    "Feeling peaceful and relaxed. #zen",
    "Just finished a challenging workout. #fitnessgoals",
    "Thinking of starting a new hobby. Any suggestions?",
    "Feeling inspired by the art exhibition I visited today. #artlover",
    "Enjoying the rainy weather with a hot cup of tea. #rainyday",
    "Feeling motivated to learn something new. #selfimprovement",
];

//array of random reactions


//get random array item, code from miniproject
const getRandomArrayItem = (array) => array[Math.floor(Math.random() * array.length)];

//generate a random username
const randomUsername = () =>
    `${getRandomArrayItem(randomAdjectiveArray)}${getRandomArrayItem(randomNounArray)}${Math.floor(Math.random() * 100)}`;

