//array of random adjectives 
const randomAdjectiveArray = [
    'amazing',
    'apathetic',
    'arrogant',
    'belligerent',
    'benevolent',
    'boring',
    'ballsy',
    'brave',
    'casual',
    'cocky',
    'crazy',
    'cute',
    'daring',
    'dashing',
    'disgusting',
    'dumb',
    'devious',
    'eager',
    'eccentric',
    'elegant',
    'evil',
    'fearless',
    'fierce',
    'friendly',
    'funky',
    'funny',
    'furious',
    'generous',
    'gigantic',
    'gloomy',
    'goofy',
    'graceful',
    'grumpy',
    'handsome',
    'happy',
    'hilarious',
    'humble',
    'hungry',
    'ignorant',
    'insane',
    'intelligent',
    'jovial',
    'juvenile',
    'kind',
    'lazy',
    'lonely',
    'lethargic',
    'lucky',
    'magnificent',
    'maniacal',
    'mellow',
    'miserable',
    'naughty',
    'nervous',
    'nice',
    'obnoxious',
    'optimistic',
    'outrageous',
    'pitiful',
    'pompous',
    'questionable',
    'quaint',
    'rational',
    'rebellious',
    'rustic',
    'sassy',
    'savage',
    'tactful',
    'tense',
    'terrifying',
    'tired',
    'tasmanian',
    'ugly',
    'unusual',
    'vicious',
    'viscous',
    'violent',
    'wacky',
    'wasteful',
    'wobbly',
    'wonderful',
    'young',
    'zany',
    'zealous'
];

//array of random nouns
const randomNounArray = [
    'aardvark',
    'albatross',
    'alligator',
    'alpaca',
    'asshole',
    'anus',
    'asphalt',
    'axolotl',
    'acorn',
    'apple',
    'banana',
    'button',
    'bucket',
    'butt',
    'butter',
    'boogers',
    'batteries',
    'biscuit',
    'cactus',
    'cannon',
    'carrot',
    'caterpillar',
    'chicken',
    'chimichanga',
    'cat',
    'dog',
    'dolphin',
    'dinosaur',
    'disappointment',
    'dishwasher',
    'dirt',
    'donkey',
    'dumpling',
    'dust',
    'earwax',
    'egg',
    'elephant',
    'eyeball',
    'fart',
    'fairy',
    'food',
    'frog',
    'giraffe',
    'goat',
    'garbage',
    'goblin',
    'gremilin',
    'gargoyle',
    'hedgehog',
    'hippo',
    'horse',
    'hamburger',
    'ice cream',
    'iguana',
    'jellyfish',
    'jerk',
    'kangaroo',
    'koala',
    'kumquat',
    'lemon',
    'lizard',
    'llama',
    'mango',
    'monkey',
    'muffin',
    'narwhal',
    'ninja',
    'noodle',
    'octopus',
    'ostrich',
    'otter',
    'panda',
    'penguin',
    'pickle',
    'pig',
    'pigeon',
    'pizza',
    'potato',
    'puppy',
    'quail',
    'quiche',
    'ravioli',
    'rhino',
    'robot',
    'sock',
    'squirrel',
    'taco',
    'toad',
    'turd',
    'turtle',
    'unicorn',
    'vampire',
    'vulture',
    'walrus',
    'waffle',
    'weasel',
    'whale',
    'worm',
    'yearbook',
    'yogurt',
    'zebra',
    'zombie'
];

//array of random thoughts
const thots = [
    "Just had the best meal ever! #foodie #yum",
    "Feeling grateful for all the wonderful people in my life. #blessed",
    "Can't wait for the weekend! #TGIF #weekendvibes",
    "Feeling inspired to start a new project. #creativity",
    "Just finished reading an amazing book. Any recommendations? #reading",
    "Missing the beach already. #summer #vacation",
    "Excited about the upcoming concert! #musiclover #livemusic",
    "Had a productive day at work. #worklife",
    "Feeling motivated to hit the gym. #fitness",
    "Enjoying the beautiful sunset. #nature",
    "Spent the day exploring new places. #adventure #travel",
    "Feeling nostalgic today. #throwback",
    "Just adopted the cutest puppy! #doglover",
    "Watching my favorite movie for the hundredth time. #movienight",
    "Feeling proud of my achievements. #accomplishment",
    "Trying out a new recipe in the kitchen. #cooking",
    "Feeling grateful for all the love and support. #gratitude",
    "Excited about the new video game release. #gaming",
    "Feeling blessed to have such amazing friends. #friendship",
    "Celebrating a special occasion tonight. #celebration",
    "Feeling peaceful and relaxed. #zen",
    "Just finished a challenging workout. #fitnessgoals",
    "Thinking of starting a new hobby. Any suggestions?",
    "Feeling inspired by the art exhibition I visited today. #artlover",
    "Enjoying the rainy weather with a hot cup of tea. #rainyday",
    "Feeling motivated to learn something new. #selfimprovement",
];

//array of random reactions
const reactions = [
    "❤️",
    "That's interesting!",
    "👍",
    "I agree with you.",
    "😄",
    "I can relate to this.",
    "😪",
    "Well said!",
    "😑",
    "Great post!",
    "🙁",
    "Thanks for sharing.",
    "😥",
    "You've got a point.",
    "👀",
    "I'm not sure about that.",
    "🌟",
    "This made me smile.",
    "👻",
    "I'm feeling inspired.",
    "😢",
    "I needed to hear this.",
    "🤯",
    "You're so right!",
    "😎",
    "This is helpful.",
    "😬",
    "I've had a similar experience.",
    "💪",
    "I disagree with you.",
    "🤗",
    "Tell me more about it.",
    "🎊",
    "I'm curious about this.",
    "😓",
    "Can you elaborate?",
    "👋",
    "I appreciate your perspective.",
    "😔",
    "This changed my mind.",
    "🥳",
    "I'm impressed!",
    "👑",
    "You're onto something here.",
    "😱",
    "I'm touched by your post.",
    "🚀",
    "I've never thought of that before.",
    "😇",
    "Interesting point of view.",
    "😃",
    "I'm with you on this.",
    "👀",
    "Thanks for the insights.",
    "😆",
    "I've been through this too.",
    "👊",
    "This made me think.",
    "😮",
    "You made my day.",
    "😴", ,
    "I can't stop thinking about your post.",
    "😋",
    "This is eye-opening.",
    "🤔",
    "You've opened my mind.",
    "👌",
    "I'm sharing this with my friends.",
    "🤭",
    "You've articulated it perfectly.",
    "🥰",
    "I've shared a similar experience.",
    "👀",
    "This is worth discussing.",
    "🙏",
    "I'm sending this to my family.",
    "💯",
    "You've got me thinking now.",
    "😂",
    "I'm going to remember this.",
    "🎉",
    "You've got a new follower.",
    "🙌",
    "This deserves more attention.",
    "🤩",
    "I'm in awe of your post.",
    "👏",
    "This is so relatable.",
    "😎",
    "I can't agree more.",
    "😊",
    "You've got my support.",
    "🔥",
    "This is so thought-provoking.",
    "😍",
    "I'm cheering for you.",
    "😁"
];

//get random array item, code from miniproject
const getRandomArrayItem = (array) => array[Math.floor(Math.random() * array.length)];

//generate a random username
const randomUsername = () =>
    `${getRandomArrayItem(randomAdjectiveArray)}${getRandomArrayItem(randomNounArray)}${Math.floor(Math.random() * 100 + 1)}`;

//generate a random thought
const randomThought = () =>  getRandomArrayItem(thots);

//generate a random reaction
const randomReaction = () => getRandomArrayItem(reactions);

//generate random amount of reactions 
const genReactions = () => {
    const reactions = [];
    reactions.length = Math.floor(Math.random() * 20 + 1);

    for(const x of reactions) {
        reactionBody: getRandomArrayItem(reactions),
    }
}

//generate a random date
const randomDate = () => {
    //creating new date object
    const date = new Date();
    //generating a random number between 0-364, (within past year)
    const randomNumberOfDays = Math.floor(Math.random() * 365);
    //setting date value to be a random day in the past year
    date.setDate(date.getDate() - randomNumberOfDays);
    //returning new date value
    return date;
}
//reactions should only be created at or after the date of original post, passing 'date' as arg
const randomDateAfter = (pastDate) => {
    //setting date as same initial value passed in
    const date = new Date(pastDate);
    //get random num days 0-31, within a month
    const randomNumberOfDays = Math.floor(Math.random() * 32);
    //adding the random number of days after the initial date 
    date.setDate(pastDate.getDate() + randomNumberOfDays);
    //returning date with new date value
    return date;
}

module.exports = { randomUsername, randomThought, randomReaction, randomDate, randomDateAfter };